title: Yoisushi 由衣的倉庫
description: I'm Yoisushi. This is my blog!

url: https://yoisushi.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
# syntax_highlighter: coderay
# highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Projects
   url: /projects
#  - title: Contact
#   url: /contact
 - title: Categories
   url: /tags

social:
   github: yoisushi
   email: sushilove777tiiin@gmail.com

# google_analytics: "UA-58263416-1"
